server:
  port: 80

spring:
  jpa:
    database: MYSQL
    generate-ddl: true
    show-sql: true
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    
logging:
  level:
    root: error
    
