id                        `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
category_id               `category_id` int(11) unsigned DEFAULT '0',
goods_sn                  `goods_sn` varchar(60) DEFAULT '',
name                      `name` varchar(120) NOT NULL DEFAULT '',
brand_id                  `brand_id` int(11) unsigned DEFAULT '0',
goods_number              `goods_number` mediumint(8) unsigned DEFAULT '0',
keywords                  `keywords` varchar(255) DEFAULT '',
goods_brief               `goods_brief` varchar(255) DEFAULT '',
goods_desc                `goods_desc` text,
is_on_sale                `is_on_sale` tinyint(1) unsigned DEFAULT '1',
add_time                  `add_time` datetime DEFAULT NULL COMMENT '修改时间',
update_time               `update_time` datetime DEFAULT NULL COMMENT '修改时间',
sort_order                `sort_order` int,
is_delete                 `is_delete` int,
attribute_category        `attribute_category` int,
counter_price             `counter_price` decimal(10,2),
extra_price               `extra_price` decimal(10,2),
is_new                    `is_new` int,
goods_unit                `goods_unit` varchar(255),
primary_pic_url           `primary_pic_url` varchar(255),
list_pic_url              `list_pic_url` varchar(255) DEFAULT NULL COMMENT '商品列表图',
retail_price              `retail_price` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '零售价格',
sell_volume               `sell_volume` int(11) unsigned DEFAULT '0' COMMENT '销售量',
primary_product_id        `primary_product_id` int(11) unsigned DEFAULT '0' COMMENT '主sku　product_id',
unit_price                `unit_price` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '单位价格，单价',
promotion_desc            `promotion_desc` varchar(255) DEFAULT NULL,
promotion_tag             `promotion_tag` varchar(45) DEFAULT NULL,
app_exclusive_price       `app_exclusive_price` decimal(10,2) unsigned DEFAULT NULL COMMENT 'APP专享价',
is_app_exclusive          `is_app_exclusive` tinyint(1) unsigned DEFAULT NULL COMMENT '是否是APP专属',
is_limited                `is_limited` tinyint(1) unsigned DEFAULT NULL,
is_hot                    `is_hot` tinyint(1) unsigned DEFAULT '0',
market_price              `market_price` decimal(10,2) DEFAULT '0.00',
create_user_id            `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
create_user_dept_id       `create_user_dept_id` bigint(20) DEFAULT NULL,
update_user_id            `update_user_id` bigint(20) DEFAULT NULL COMMENT '修改人ID',
                          
                          
                          